<?xml version="1.0" encoding="utf-8"?>
<!-- ========================================== -->
<!-- Reusable Domain Config                     -->
<!-- ========================================== -->
<domains>
  <domain oid="1188594552974">
    <code>Dm</code>
    <type>Reusable</type>
    <packageCode />
    <abstraction>false</abstraction>
    <defaultConstruct>false</defaultConstruct>
    <packagePrefix />
    <referenceModel>Reference</referenceModel>
    <i18n>false</i18n>
    <signin>false</signin>
    <signinConcept>Member</signinConcept>
    <shortTextDefaultLength>64</shortTextDefaultLength>
    <pageBlockDefaultSize>16</pageBlockDefaultSize>
    <validateForm>true</validateForm>
    <confirmRemove>true</confirmRemove>
    <models>
      <model oid="1169577221985">
        <code>MetaDefinition</code>
        <abstraction>false</abstraction>
        <author>Dzenan Ridjanovic</author>
        <packageCode />
        <persistent>true</persistent>
        <persistenceType>xml</persistenceType>
        <persistenceRelativePath>data/xml/dm/meta</persistenceRelativePath>
        <persistenceConfig />
        <defaultLoadSave>true</defaultLoadSave>
        <datePattern>yyyy-MM-dd</datePattern>
        <session>false</session>
        <concepts>
          <concept oid="1169577222271">
            <code>DomainModel</code>
            <abstraction>false</abstraction>
            <entitiesCode>DomainModels</entitiesCode>
            <packageCode />
            <min>0</min>
            <max>N</max>
            <entry>false</entry>
            <fileName />
            <index>false</index>
            <display>true</display>
            <displayType>table</displayType>
            <add>true</add>
            <remove>true</remove>
            <update>true</update>
            <properties>
              <property oid="1169577222273">
                <code>code</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444565857">
                <code>abstraction</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222274">
                <code>extension</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444590233">
                <code>extensionDomain</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1191442513330">
                <code>extensionDomainType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222275">
                <code>extensionModel</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222276">
                <code>author</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1182892833345">
                <code>packageCode</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222278">
                <code>persistent</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222279">
                <code>persistenceType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222280">
                <code>persistenceRelativePath</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222281">
                <code>persistenceConfig</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222282">
                <code>defaultLoadSave</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222306">
                <code>datePattern</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222283">
                <code>session</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
            </properties>
            <neighbors>
              <neighbor oid="1169577222462">
                <code>concepts</code>
                <destinationConcept>Concept</destinationConcept>
                <inverseNeighbor>domainModel</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>child</type>
                <min>0</min>
                <max>N</max>
                <unique>false</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>false</absorb>
              </neighbor>
              <neighbor oid="1170444346812">
                <code>domain</code>
                <destinationConcept>Domain</destinationConcept>
                <inverseNeighbor>domainModels</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>parent</type>
                <min>1</min>
                <max>1</max>
                <unique>true</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>true</absorb>
              </neighbor>
            </neighbors>
          </concept>
          <concept oid="1169577222309">
            <code>Concept</code>
            <abstraction>false</abstraction>
            <entitiesCode>Concepts</entitiesCode>
            <packageCode />
            <min>0</min>
            <max>N</max>
            <entry>false</entry>
            <fileName />
            <index>false</index>
            <display>true</display>
            <displayType>table</displayType>
            <add>true</add>
            <remove>true</remove>
            <update>true</update>
            <properties>
              <property oid="1169577222311">
                <code>code</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444821547">
                <code>abstraction</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222312">
                <code>extension</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444833657">
                <code>extensionDomain</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1191442579221">
                <code>extensionDomainType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169591250422">
                <code>extensionModel</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222313">
                <code>extensionConcept</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444858674">
                <code>extensionWithNeighbors</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222314">
                <code>entitiesCode</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1188594656785">
                <code>packageCode</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222334">
                <code>min</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222335">
                <code>max</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222331">
                <code>entry</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222332">
                <code>fileName</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170867213922">
                <code>index</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222336">
                <code>display</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222337">
                <code>displayType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222338">
                <code>add</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222339">
                <code>remove</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222340">
                <code>update</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
            </properties>
            <neighbors>
              <neighbor oid="1169577222463">
                <code>properties</code>
                <destinationConcept>Property</destinationConcept>
                <inverseNeighbor>concept</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>child</type>
                <min>0</min>
                <max>N</max>
                <unique>false</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>false</absorb>
              </neighbor>
              <neighbor oid="1169577222464">
                <code>neighbors</code>
                <destinationConcept>Neighbor</destinationConcept>
                <inverseNeighbor>concept</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>child</type>
                <min>0</min>
                <max>N</max>
                <unique>false</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>false</absorb>
              </neighbor>
              <neighbor oid="1169577222462">
                <code>domainModel</code>
                <destinationConcept>DomainModel</destinationConcept>
                <inverseNeighbor>concepts</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>parent</type>
                <min>1</min>
                <max>1</max>
                <unique>true</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>true</absorb>
              </neighbor>
            </neighbors>
          </concept>
          <concept oid="1169577222356">
            <code>Property</code>
            <abstraction>false</abstraction>
            <entitiesCode>Properties</entitiesCode>
            <packageCode />
            <min>0</min>
            <max>N</max>
            <entry>false</entry>
            <fileName />
            <index>false</index>
            <display>true</display>
            <displayType>table</displayType>
            <add>true</add>
            <remove>true</remove>
            <update>true</update>
            <properties>
              <property oid="1169577222358">
                <code>code</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222359">
                <code>extension</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222360">
                <code>extensiopnProperty</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222361">
                <code>propertyClass</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1190652973063">
                <code>derived</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222362">
                <code>validateType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222363">
                <code>validationType</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222364">
                <code>maxLength</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222365">
                <code>required</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1182893111393">
                <code>sensitive</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222366">
                <code>defaultValue</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222368">
                <code>autoIncrement</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222367">
                <code>unique</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170867302439">
                <code>index</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222369">
                <code>reference</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222386">
                <code>referenceNeighbor</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222387">
                <code>display</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222388">
                <code>update</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222389">
                <code>displayLength</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222390">
                <code>essential</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222391">
                <code>scramble</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1189525258594">
                <code>whitespaceAllowed</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
            </properties>
            <neighbors>
              <neighbor oid="1169577222463">
                <code>concept</code>
                <destinationConcept>Concept</destinationConcept>
                <inverseNeighbor>properties</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>parent</type>
                <min>1</min>
                <max>1</max>
                <unique>true</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>true</absorb>
              </neighbor>
            </neighbors>
          </concept>
          <concept oid="1169577222392">
            <code>Neighbor</code>
            <abstraction>false</abstraction>
            <entitiesCode>Neighbors</entitiesCode>
            <packageCode />
            <min>0</min>
            <max>N</max>
            <entry>false</entry>
            <fileName />
            <index>false</index>
            <display>true</display>
            <displayType>table</displayType>
            <add>true</add>
            <remove>true</remove>
            <update>true</update>
            <properties>
              <property oid="1169577222394">
                <code>code</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222395">
                <code>extension</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222396">
                <code>extensionNeighbor</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222397">
                <code>destinationConcept</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222398">
                <code>inverseNeighbor</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170445144206">
                <code>internal</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1173790833297">
                <code>partOfManyToMany</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222415">
                <code>type</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222416">
                <code>min</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222417">
                <code>max</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222418">
                <code>unique</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1182893293225">
                <code>index</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222419">
                <code>addRule</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222420">
                <code>removeRule</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222421">
                <code>updateRule</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222422">
                <code>display</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222423">
                <code>update</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1169577222424">
                <code>absorb</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
            </properties>
            <neighbors>
              <neighbor oid="1169577222464">
                <code>concept</code>
                <destinationConcept>Concept</destinationConcept>
                <inverseNeighbor>neighbors</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>parent</type>
                <min>1</min>
                <max>1</max>
                <unique>true</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>true</absorb>
              </neighbor>
            </neighbors>
          </concept>
          <concept oid="1170444314169">
            <code>Domain</code>
            <abstraction>false</abstraction>
            <entitiesCode>Domains</entitiesCode>
            <packageCode />
            <min>0</min>
            <max>N</max>
            <entry>true</entry>
            <fileName>domain.xml</fileName>
            <index>false</index>
            <display>true</display>
            <displayType>table</displayType>
            <add>true</add>
            <remove>true</remove>
            <update>true</update>
            <properties>
              <property oid="1170444352688">
                <code>code</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1191442425032">
                <code>type</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>true</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>true</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>true</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1182892726376">
                <code>packageCode</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444406595">
                <code>abstraction</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444413971">
                <code>defaultConstruct</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444425425">
                <code>packagePrefix</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444431520">
                <code>referenceModel</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444447818">
                <code>i18n</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444452319">
                <code>signin</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444460914">
                <code>signinConcept</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444484759">
                <code>shortTextDefaultLength</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444500604">
                <code>pageBlockDefaultSize</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444517511">
                <code>validateForm</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
              <property oid="1170444521965">
                <code>confirmRemove</code>
                <propertyClass>java.lang.String</propertyClass>
                <derived>false</derived>
                <validateType>false</validateType>
                <validationType />
                <maxLength>0</maxLength>
                <required>false</required>
                <sensitive>false</sensitive>
                <defaultValue />
                <autoIncrement>false</autoIncrement>
                <unique>false</unique>
                <index>false</index>
                <reference>false</reference>
                <referenceNeighbor />
                <display>true</display>
                <update>true</update>
                <displayLength>0</displayLength>
                <essential>false</essential>
                <scramble>false</scramble>
                <whitespaceAllowed>true</whitespaceAllowed>
                <referenceDropDownLookup>false</referenceDropDownLookup>
              </property>
            </properties>
            <neighbors>
              <neighbor oid="1170444346812">
                <code>domainModels</code>
                <destinationConcept>DomainModel</destinationConcept>
                <inverseNeighbor>domain</inverseNeighbor>
                <partOfManyToMany>false</partOfManyToMany>
                <type>child</type>
                <min>0</min>
                <max>N</max>
                <unique>false</unique>
                <index>false</index>
                <addRule>NONE</addRule>
                <removeRule>NONE</removeRule>
                <updateRule>NONE</updateRule>
                <display>true</display>
                <update>true</update>
                <absorb>false</absorb>
              </neighbor>
            </neighbors>
          </concept>
        </concepts>
      </model>
    </models>
  </domain>
</domains>