<?xml version="1.0" encoding="utf-8"?>
<domains>
  <origin>OpenModelSphere 3.2</origin>
  <domain>
    <code>Modelibra</code>
    <models>
      <model idmodel="1" idref="0">
        <code>Relational Data Model</code>
        <concepts>
          <concept>
            <code>Domain</code>
            <description text="Descripcion larga é con caracteres unicode ô à " />
            <properties>
              <property>
                <code>domaiType</code>
                <description text="Otra descripcion é{à " />
              </property>
              <property>
                <code>origin</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Domain" baseMax="N" baseMin="0" code="Domain-Domain" refConcept="Domain" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" code="MetaObj-Domain" refConcept="Domain" />
            </foreigns>
          </concept>
          <concept>
            <code>Model</code>
            <properties>
              <property>
                <code>modelType</code>
              </property>
              <property>
                <code>modelPrefix</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Domain" baseMax="N" baseMin="0" code="Domain-Model" refConcept="Model" refMax="1" refMin="1" />
              <foreign baseConcept="Domain" baseMax="N" baseMin="0" code="Domain-Model" refConcept="Model" refMax="1" refMin="1" />
              <foreign baseConcept="Model" baseMax="N" baseMin="0" code="extModel" pairName="Model-Model" refConcept="Model" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" code="MetaObj-Model" refConcept="Model" />
            </foreigns>
          </concept>
          <concept>
            <code>Concept</code>
            <properties>
              <property>
                <code>conceptType</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Model" baseMax="N" baseMin="0" code="Model-Concept" refConcept="Concept" refMax="1" refMin="1" />
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="extConcept" pairName="Concept-Concept" refConcept="Concept" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" code="MetaObj-Concept" refConcept="Concept" />
            </foreigns>
          </concept>
          <concept>
            <code>Relationship</code>
            <properties>
              <property>
                <code>relationType</code>
              </property>
              <property>
                <code>baseMin</code>
              </property>
              <property>
                <code>baseMax</code>
              </property>
              <property>
                <code>refMin</code>
              </property>
              <property>
                <code>refMax</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-Relationship" refConcept="Relationship" refMax="1" refMin="1" />
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-Relationship" refConcept="Relationship" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>Property</code>
            <properties>
              <property>
                <code>propertyType</code>
              </property>
              <property>
                <code>classType</code>
              </property>
              <property>
                <code>length</code>
              </property>
              <property>
                <code>decLength</code>
              </property>
              <property>
                <code>nullable</code>
              </property>
              <property>
                <code>required</code>
              </property>
              <property>
                <code>defaultValue</code>
              </property>
              <property>
                <code>sensitive</code>
              </property>
              <property>
                <code>essential</code>
              </property>
              <property>
                <code>unique</code>
              </property>
              <property>
                <code>propertyIndex</code>
              </property>
              <property>
                <code>foreign</code>
              </property>
              <property>
                <code>foreignConcept</code>
              </property>
              <property>
                <code>foreignProperty</code>
              </property>
              <property>
                <code>validationRule</code>
              </property>
              <property>
                <code>derivationType</code>
              </property>
              <property>
                <code>derivationRule</code>
              </property>
              <property>
                <code>derivationConcept</code>
              </property>
              <property>
                <code>derivationProperty</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-Property" refConcept="Property" refMax="1" refMin="1" />
              <foreign baseConcept="Relationship" code="Relationship-Property" refConcept="Property" refMax="1" refMin="1" />
              <foreign baseConcept="Relationship" code="Relationship-Property" refConcept="Property" />
              <foreign baseConcept="Property" baseMax="N" baseMin="0" code="extProperty" pairName="Property-Property" refConcept="Property" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" code="MetaObj-Property" refConcept="Property" />
            </foreigns>
          </concept>
          <concept>
            <code>Table</code>
            <properties />
            <foreigns />
          </concept>
          <concept>
            <code>MetaObj</code>
            <properties>
              <property>
                <code>code</code>
              </property>
              <property>
                <code>objType</code>
              </property>
              <property>
                <code>description</code>
              </property>
              <property>
                <code>extensionType</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="MetaObj" baseMax="N" baseMin="0" code="extObj" pairName="MetaObj-MetaObj" refConcept="MetaObj" refMax="1" refMin="1" />
              <foreign baseConcept="UserDefinedProperty" baseMax="N" baseMin="0" code="UserDefinedProperty-MetaObj" refConcept="MetaObj" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>Table</code>
            <properties />
            <foreigns />
          </concept>
          <concept>
            <code>UserDefinedProperty</code>
            <properties>
              <property>
                <code>udpCode</code>
              </property>
              <property>
                <code>udpTarget</code>
              </property>
              <property>
                <code>udpType</code>
              </property>
              <property>
                <code>udpValue</code>
              </property>
              <property>
                <code>udpRule</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="MetaObj" baseMax="N" baseMin="0" code="MetaObj-UserDefinedProperty" refConcept="UserDefinedProperty" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>MetaLink</code>
            <properties>
              <property>
                <code>synonymType</code>
              </property>
              <property>
                <code>synonymDescription</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="MetaObj" baseMax="N" baseMin="0" code="MetaObj-MetaLink" refConcept="MetaLink" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" baseMax="N" baseMin="0" code="MetaObj-MetaLink" refConcept="MetaLink" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>NavigationLink</code>
            <properties>
              <property>
                <code>navigationType</code>
              </property>
              <property>
                <code>navigationRule</code>
              </property>
              <property>
                <code>caption</code>
              </property>
              <property>
                <code>toolTip</code>
              </property>
              <property>
                <code>tag</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-NavigationLink" refConcept="NavigationLink" refMax="1" refMin="1" />
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-NavigationLink" refConcept="NavigationLink" refMax="1" refMin="1" />
              <foreign baseConcept="Concept" baseMax="N" baseMin="0" code="Concept-NavigationLink" refConcept="NavigationLink" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>EntryPoints</code>
            <properties>
              <property>
                <code>caption</code>
              </property>
              <property>
                <code>titre</code>
              </property>
              <property>
                <code>typeEntryPoint</code>
              </property>
              <property>
                <code>rule</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Concept" baseMax="1" baseMin="0" code="Concept-EntryPoints" refConcept="EntryPoints" refMax="1" refMin="0" />
              <foreign baseConcept="MetaObj" code="MetaObj-EntryPoints" refConcept="EntryPoints" />
              <foreign baseConcept="Domain" baseMax="N" baseMin="0" code="Domain-EntryPoints" refConcept="EntryPoints" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>Menu</code>
            <properties>
              <property>
                <code>menuCode</code>
              </property>
              <property>
                <code>menuBase</code>
              </property>
              <property>
                <code>menuIndex</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="EntryPoints" baseMax="N" baseMin="0" code="EntryPoints-Menu" refConcept="Menu" refMax="1" refMin="1" />
              <foreign baseConcept="MetaObj" code="MetaObj-Menu" refConcept="Menu" />
            </foreigns>
          </concept>
          <concept>
            <code>ModelGraphic</code>
            <properties>
              <property>
                <code>modelName</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="Model" baseMax="N" baseMin="0" code="Model-ModelGraphic" refConcept="ModelGraphic" refMax="1" refMin="1" />
            </foreigns>
          </concept>
          <concept>
            <code>Traduction</code>
            <properties>
              <property>
                <code>languageCode</code>
              </property>
              <property>
                <code>caption</code>
              </property>
              <property>
                <code>description</code>
              </property>
            </properties>
            <foreigns>
              <foreign baseConcept="MetaObj" baseMax="N" baseMin="0" code="MetaObj-Traduction" refConcept="Traduction" refMax="1" refMin="1" />
            </foreigns>
          </concept>
        </concepts>
      </model>
    </models>
  </domain>
</domains>