<?xml version="1.0" encoding="UTF-8"?>
<domains>
<name>TCO</name>
<origin>OpenModelSphere 3.2</origin>
<udfs/>
<domain idmodel="1" idref="0" name="Relational Data Model">
<tables>
<table alias="" name="Famille" physicalName="" superTable="">
<column alias="" foreign="False" name="Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Logiciel" physicalName="" superTable="">
<column alias="" foreign="False" name="Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Durée cycle" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="description" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Fonction" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Commentaire" nullable="False" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Famille Nom" nullable="False" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Type logiciel Type logiciel" nullable="False" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Éditeur" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Référence" physicalName="" superTable="">
<column alias="" foreign="False" name="Étiquette" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Enregistrement BibTex" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Profil cycle" physicalName="" superTable="">
<column alias="" foreign="False" name="Année" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût acquisition" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût maintenance" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût formation" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût support" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Coût adhérance" physicalName="" superTable="">
<column alias="" foreign="False" name="Coût évolution" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût substitution" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Niveau Niveau" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Niveau" physicalName="" superTable="">
<column alias="" foreign="False" name="Niveau" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Profil" physicalName="" superTable="">
<column alias="" foreign="False" name="Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Description" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Sources" physicalName="" superTable="">
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Référence Étiquette" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Composition pofil" physicalName="" superTable="">
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Profil Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Commentaire" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Type logiciel" physicalName="" superTable="">
<column alias="" foreign="False" name="Type logiciel" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Organisation" physicalName="" superTable="">
<column alias="" foreign="False" name="Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="SIO" physicalName="" superTable="">
<column alias="" foreign="False" name="Nombre" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Profil Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Organisation Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Sénario" physicalName="" superTable="">
<column alias="" foreign="False" name="Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Version" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Durée" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="NIveau" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Description" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Organisation Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Type logiciel Type logiciel" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Composition sénario" physicalName="" superTable="">
<column alias="" foreign="False" name="Année début" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Année fin" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="nombre" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Version" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Organisation Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Profil Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="TCO" physicalName="" superTable="">
<column alias="" foreign="False" name="Année" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="TCO" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût acquisition" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût maintenance" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût formation" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût support" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance  OS" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance général" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance Maitier acquis" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance Maitier maison" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Version" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Organisation Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
<table alias="" name="Spécification Logiciel" physicalName="" superTable="">
<column alias="" foreign="False" name="Date début" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Date fin" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Nombre" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût acquisition" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût maintenance" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût support" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût formation" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance OS" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance général" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance Métier acquis" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="False" name="Coût adhérance Métier acquis" nullable="True" physicalName="" primary="False" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Version" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Logiciel Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
<column alias="" foreign="True" name="Sénario Organisation Nom" nullable="False" physicalName="" primary="True" superColumn="" type="?">
<udfs>
<udf description=""/>
</udfs>
</column>
</table>
</tables>
<relations>
<relation LogicalName="" name="Famille-Logiciel">
<r0 cardianlity="0..N" multiplicity="MANY" name="Famille"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Logiciel">
<refCol name="Famille Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-Profil cycle">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Profil cycle">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-Coût adhérance">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Coût adhérance">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Niveau-Coût adhérance">
<r0 cardianlity="0..N" multiplicity="MANY" name="Niveau"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Coût adhérance">
<refCol name="Niveau Niveau"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-Sources">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Sources">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Référence-Sources">
<r0 cardianlity="0..N" multiplicity="MANY" name="Référence"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Sources">
<refCol name="Référence Étiquette"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-Composition pofil">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Composition pofil">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Profil-Composition pofil">
<r0 cardianlity="0..N" multiplicity="MANY" name="Profil"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Composition pofil">
<refCol name="Profil Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Profil-SIO">
<r0 cardianlity="0..N" multiplicity="MANY" name="Profil"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="SIO">
<refCol name="Profil Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Organisation-SIO">
<r0 cardianlity="0..N" multiplicity="MANY" name="Organisation"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="SIO">
<refCol name="Organisation Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Organisation-Sénario">
<r0 cardianlity="0..N" multiplicity="MANY" name="Organisation"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Sénario">
<refCol name="Organisation Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Sénario-Composition sénario">
<r0 cardianlity="0..N" multiplicity="MANY" name="Sénario"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Composition sénario">
<refCol name="Sénario Organisation Nom"/>
<refCol name="Sénario Nom"/>
<refCol name="Sénario Version"/>
</r1>
</relation>
<relation LogicalName="" name="Sénario-TCO">
<r0 cardianlity="0..N" multiplicity="MANY" name="Sénario"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="TCO">
<refCol name="Sénario Organisation Nom"/>
<refCol name="Sénario Nom"/>
<refCol name="Sénario Version"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-TCO">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="TCO">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Type logiciel-Sénario">
<r0 cardianlity="0..N" multiplicity="MANY" name="Type logiciel"/>
<r1 cardianlity="0..1" multiplicity="OPTIONAL" name="Sénario">
<refCol name="Type logiciel Type logiciel"/>
</r1>
</relation>
<relation LogicalName="" name="Sénario-Spécification Logiciel">
<r0 cardianlity="0..N" multiplicity="MANY" name="Sénario"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Spécification Logiciel">
<refCol name="Sénario Organisation Nom"/>
<refCol name="Sénario Nom"/>
<refCol name="Sénario Version"/>
</r1>
</relation>
<relation LogicalName="" name="Logiciel-Spécification Logiciel">
<r0 cardianlity="0..N" multiplicity="MANY" name="Logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Spécification Logiciel">
<refCol name="Logiciel Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Profil-Composition sénario">
<r0 cardianlity="0..N" multiplicity="MANY" name="Profil"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Composition sénario">
<refCol name="Profil Nom"/>
</r1>
</relation>
<relation LogicalName="" name="Type logiciel-Logiciel">
<r0 cardianlity="0..N" multiplicity="MANY" name="Type logiciel"/>
<r1 cardianlity="1..1" multiplicity="EXACTLY_ONE" name="Logiciel">
<refCol name="Type logiciel Type logiciel"/>
</r1>
</relation>
</relations>
</domain>
<linkModels/>
</domains>
